// src/lib/supabase/database.types.ts
export type Database = {
  public: {
    Tables: {
      salary_loan_applications: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          national_id: string;
          date_of_birth: string;
          gender: string;
          residential_address: string;
          email: string;
          cell_number: string;
          marital_status: string;
          dependents: number;
          education_level: string;
          employer_name: string;
          employer_address: string;
          department: string;
          employee_number: string;
          job_title: string;
          employment_start_date: string;
          employment_status: string;
          hr_name: string;
          hr_number: string;
          gross_salary: number;
          net_salary: number;
          other_income: string;
          household_expenses: number;
          debts: any;
          loan_amount: number;
          loan_purpose: string;
          repayment_period: string;
          repayment_frequency: string;
          id_copy_url: string | null;
          proof_of_residence_url: string | null;
          payslip_url: string | null;
          bank_statements_url: string | null;
          employer_letter_url: string | null;
          photos_url: string | null;
          declaration_accepted: boolean;
          guarantee_accepted: boolean;
          voluntary_surrender_accepted: boolean;
          power_of_attorney_accepted: boolean;
          affidavit_accepted: boolean;
          agreement_accepted: boolean;
          status: string;
          submitted_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          national_id: string;
          date_of_birth: string;
          gender: string;
          residential_address: string;
          email: string;
          cell_number: string;
          marital_status: string;
          dependents: number;
          education_level: string;
          employer_name: string;
          employer_address: string;
          department: string;
          employee_number: string;
          job_title: string;
          employment_start_date: string;
          employment_status: string;
          hr_name: string;
          id_copy_url?: string | null;
          proof_of_residence_url?: string | null;
          payslip_url?: string | null;
          bank_statements_url?: string | null;
          employer_letter_url?: string | null;
          photos_url?: string | null;
          declaration_accepted: boolean;
          guarantee_accepted: boolean;
          voluntary_surrender_accepted: boolean;
          power_of_attorney_accepted: boolean;
          affidavit_accepted: boolean;
          agreement_accepted: boolean;
          status?: string;
          submitted_at?: string;
        };

          id?: string;
          user_id: string;
          full_name: string;
          national_id: string;
          date_of_birth: string;
          gender: string;
          residential_address: string;
          email: string;
          cell_number: string;
          marital_status: string;
          dependents: number;
          education_level: string;
          employer_name: string;
          employer_address: string;
          department: string;
          employee_number: string;
          job_title: string;
          employment_start_date: string;
          employment_status: string;
          hr_name: string;
          hr_number: string;
          gross_salary: number;
          net_salary: number;
          other_income: string;
          household_expenses: number;
          debts: any;
          loan_amount: number;
          loan_purpose: string;
          repayment_period: string;
          repayment_frequency: string;
          id_copy_url: string | null;
          proof_of_residence_url: string | null;
          payslip_url: string | null;
          bank_statements_url: string | null;
          employer_letter_url: string | null;
          photos_url: string | null;
          declaration_accepted: boolean;
          guarantee_accepted: boolean;
          voluntary_surrender_accepted: boolean;
          power_of_attorney_accepted: boolean;
          affidavit_accepted: boolean;
          agreement_accepted: boolean;
          status?: string;
          submitted_at?: string;
        };
        Update: Partial<{
          id?: string;
          user_id?: string;
          full_name?: string;
          national_id?: string;
          date_of_birth?: string;
          gender?: string;
          residential_address?: string;
          email?: string;
          cell_number?: string;
          marital_status?: string;
          dependents?: number;
          education_level?: string;
          employer_name?: string;
          employer_address?: string;
          department?: string;
          employee_number?: string;
          job_title?: string;
          employment_start_date?: string;
          employment_status?: string;
          hr_name?: string;
          hr_number?: string;
          gross_salary?: number;
          net_salary?: number;
          other_income?: string;
          household_expenses?: number;
          debts?: any;
          loan_amount?: number;
          loan_purpose?: string;
          repayment_period?: string;
          repayment_frequency?: string;
          id_copy_url?: string | null;
          proof_of_residence_url?: string | null;
          payslip_url?: string | null;
          bank_statements_url?: string | null;
          employer_letter_url?: string | null;
          photos_url?: string | null;
          declaration_accepted?: boolean;
          guarantee_accepted?: boolean;
          voluntary_surrender_accepted?: boolean;
          power_of_attorney_accepted?: boolean;
          affidavit_accepted?: boolean;
          agreement_accepted?: boolean;
          status?: string;
          submitted_at?: string;
        }>;
      },
      business_loan_applications: {
        Row: {
          id: string;
          cell_number: string;
          marital_status: string;
          dependents: number;
          education_level: string;
          employer_name: string;
          employer_address: string;
          department: string;
          employee_number: string;
          job_title: string;
          employment_start_date: string;
          employment_status: string;
          hr_name: string;
          hr_number: string;
          gross_salary: number;
          net_salary: number;
          other_income: string;
          household_expenses: number;
          debts: any;
          loan_amount: number;
          loan_purpose: string;
          repayment_period: string;
          repayment_frequency: string;
          id_copy_url: string | null;
          proof_of_residence_url: string | null;
          payslip_url: string | null;
          bank_statements_url: string | null;
          employer_letter_url: string | null;
          photos_url: string | null;
          declaration_accepted: boolean;
          guarantee_accepted: boolean;
          voluntary_surrender_accepted: boolean;
          power_of_attorney_accepted: boolean;
          affidavit_accepted: boolean;
          agreement_accepted: boolean;
          status: string;
          submitted_at: string;
          legal_business_name: string;
          trading_name: string | null;
          registration_number: string;
          date_of_registration: string;
          tax_identification_number: string | null;
          vat_number: string | null;
          business_sector: string;
          industry: string;
          years_in_business: number;
          number_of_employees: number;
          business_structure: string;
          business_address: string;
          city: string;
          province: string;
          postal_code: string;
          business_email: string;
          business_phone: string;
          website: string | null;
          business_description: string;
          annual_turnover: number;
          projected_turnover: number;
          gross_profit: number;
          net_profit: number;
          bank_name: string;
          account_number: string;
          average_balance: number;
          financial_statements_url: string | null;
          tax_returns_url: string | null;
          loan_term: number;
          collateral_items: any | null; // Adjust type as needed
          business_plan_url: string | null;
          collateral_documents_url: string | null;
          other_documents_url: string | null;
          references: any; // Adjust type as needed
          declarations: any; // Adjust type as needed
          created_at: string;
          updated_at: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: {
          id?: string;
          application_number?: string;
          user_id: string;
          status?: string;
          legal_business_name: string;
          trading_name?: string | null;
          registration_number: string;
          date_of_registration: string;
          tax_identification_number?: string | null;
          vat_number?: string | null;
          business_sector: string;
          industry: string;
          years_in_business: number;
          number_of_employees: number;
          business_structure: string;
          business_address: string;
          city: string;
          province: string;
          postal_code: string;
          business_email: string;
          business_phone: string;
          website?: string | null;
          business_description: string;
          annual_turnover: number;
          projected_turnover: number;
          gross_profit: number;
          net_profit: number;
          bank_name: string;
          account_number: string;
          average_balance: number;
          financial_statements_url?: string | null;
          bank_statements_url?: string | null;
          tax_returns_url?: string | null;
          loan_amount: number;
          loan_term: number;
          repayment_frequency: string;
          loan_purpose: string;
          collateral_items?: any | null;
          business_plan_url?: string | null;
          collateral_documents_url?: string | null;
          other_documents_url?: string | null;
          references: any;
          declarations: any;
          created_at?: string;
          updated_at?: string;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Update: Partial<{
          id?: string;
          application_number?: string;
          user_id?: string;
          status?: string;
          legal_business_name?: string;
          trading_name?: string | null;
          registration_number?: string;
          date_of_registration?: string;
          tax_identification_number?: string | null;
          vat_number?: string | null;
          business_sector?: string;
          industry?: string;
          years_in_business?: number;
          number_of_employees?: number;
          business_structure?: string;
          business_address?: string;
          city?: string;
          province?: string;
          postal_code?: string;
          business_email?: string;
          business_phone?: string;
          website?: string | null;
          business_description?: string;
          annual_turnover?: number;
          projected_turnover?: number;
          gross_profit?: number;
          net_profit?: number;
          bank_name?: string;
          account_number?: string;
          average_balance?: number;
          financial_statements_url?: string | null;
          bank_statements_url?: string | null;
          tax_returns_url?: string | null;
          loan_amount?: number;
          loan_term?: number;
          repayment_frequency?: string;
          loan_purpose?: string;
          collateral_items?: any | null;
          business_plan_url?: string | null;
          collateral_documents_url?: string | null;
          other_documents_url?: string | null;
          references?: any;
          declarations?: any;
          updated_at?: string;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        }>;
      },
      business_loan_owners: {
        Row: {
          id: string;
          application_id: string;
          full_name: string;
          id_number: string;
          date_of_birth: string;
          gender: string;
          residential_address: string;
          email: string;
          phone_number: string;
          marital_status: string;
          position: string;
          ownership_percentage: number;
          bank_name: string;
          account_number: string;
          average_monthly_balance: number;
          next_of_kin_name: string;
          next_of_kin_relationship: string;
          next_of_kin_address: string;
          next_of_kin_phone: string;
          next_of_kin_id_number: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          full_name: string;
          id_number: string;
          date_of_birth: string;
          gender: string;
          residential_address: string;
          email: string;
          phone_number: string;
          marital_status: string;
          position: string;
          ownership_percentage: number;
          bank_name: string;
          account_number: string;
          average_monthly_balance: number;
          next_of_kin_name: string;
          next_of_kin_relationship: string;
          next_of_kin_address: string;
          next_of_kin_phone: string;
          next_of_kin_id_number: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          full_name?: string;
          id_number?: string;
          date_of_birth?: string;
          gender?: string;
          residential_address?: string;
          email?: string;
          phone_number?: string;
          marital_status?: string;
          position?: string;
          ownership_percentage?: number;
          bank_name?: string;
          account_number?: string;
          average_monthly_balance?: number;
          next_of_kin_name?: string;
          next_of_kin_relationship?: string;
          next_of_kin_address?: string;
          next_of_kin_phone?: string;
          next_of_kin_id_number?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };