// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhxqcailvqjegovwhcvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoeHFjYWlsdnFqZWdvdndoY3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODA1MTMsImV4cCI6MjA2OTY1NjUxM30.9opCz-8bgC3na5lH2GnVa3m7wt7z7hNnwag9JjlZlT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});